### ISSUE TITLE
No sample sound on iPhone 12 Pro Max

### ISSUE THREAD

**Issue by geekedtv** [kaythomas0/noisedash#10]
I tried both Firefox and Safari and get no sound.

I tried other apps like youtube and music to verify it's not a user sound issue and they work so it doesn't appear to be a phone issue.

I do get sound on my laptop browser using Firefox.

Seems to be an issue with Tone.js maybe related here https://github.com/Tonejs/Tone.js/issues/954

**Comment by kaythomas0** [comment]
I tried the fix listed in that issue and it still wasn't working, will have to keep looking into it

**Comment by geekedtv** [comment]
> I tried the fix listed in that issue and it still wasn't working, will have to keep looking into it

Ok thanks for the update!

**Comment by kaythomas0** [comment]
Hey @geekedtv I just realized, with the iPhone I tested with, silent mode was on. When I turned that off, it was working. Is that on on your iPhone too?

**Comment by kaythomas0** [comment]
Apparently web audio is muted by default when silent mode is on, I even found a package that looks like it can fix that: https://github.com/swevans/unmute

**Comment by kaythomas0** [comment]
I believe this was happening because of silent mode being on.
