### ISSUE TITLE
Did the same sample would generate same sound output ?

### ISSUE THREAD

**Issue by nautilux2** [kaythomas0/noisedash#11]

**Comment by nautilux2** [comment]
I mean with the same sample like rain.mp3 and same input params, did noisedash will generate the same output ?

**Comment by kaythomas0** [comment]
Oh I see! The sample like rain.mp3 should always be the same output (and you can control the volume), but the noise that is generated is generated in real time I believe, so I think it will technically be different.

**Comment by nautilux2** [comment]
Thanks
