### ISSUE TITLE
Ability to download file

### ISSUE THREAD

**Issue by a-camacho** [kaythomas0/noisedash#13]
Would it be possible to allow downloading an MP3 (or other format) file of defined profile, for external use ?

Thanks a lot !
Great tool !

**Comment by kaythomas0** [comment]
I think I may be able to leverage the [Recorder](https://tonejs.github.io/docs/14.7.77/Recorder) in Tone.js to do this, will look into it, thanks!

**Comment by kaythomas0** [comment]
Added in v0.3.0
