### ISSUE TITLE
[feature] Random/Periodic sample triggers

### ISSUE THREAD

**Issue by subatomiq** [kaythomas0/noisedash#25]
HI, i would really like to be able to set our samples to fire at either random (preferably) or periodic intervals, or both
...e.g. if you have a short bell sound that would be horribly annoying if it just looped every length of the sample,
but could be quite beautiful if it only triggered once every minute or so (random within a range would be absolutely ideal)

**Comment by kaythomas0** [comment]
I like it, good idea! I can look into trying to implement that in the coming releases.

**Comment by torwag** [comment]
Larger samples might benefit from not only being played randomly, but also starting the sample randomly. E.g. some samples might have a very characteristic start, which people recognize as "ah this sample" playing it not right from the beginning, but skipping a random amount of seconds creates some randomness into it.
One would have to make sure, there are no "hard" skips, so maybe phasing in and out or searching for silent parts to be skipped too.

**Comment by kaythomas0** [comment]
Released in https://github.com/kaythomas0/noisedash/releases/tag/v0.6.0
