### ISSUE TITLE
Are there any downloadable samples and profiles ?

### ISSUE THREAD

**Issue by jasek5** [kaythomas0/noisedash#26]
Hi,

awesome project!

I am just curious if there is any place on the internet where I can download any samples or finished sounds/noises.
If so, can anyone recommend me one?

Thank you very much!

**Comment by kaythomas0** [comment]
For sharing profiles, I figured the [Discussions](https://github.com/kaythomas0/noisedash/discussions) page of this repo would be a good place to do that (this tool is still pretty new and not too popular right now though, so no one has done that yet). There's a post there about favorite samples and I discussed that I like using https://freesound.org to find samples. I personally like listening to deep brown noise with rain and thunder to sleep and I can get good rain and thunder sounds from that site.

Hopefully as more features get added (I'm working on more sound effects and https://github.com/kaythomas0/noisedash/issues/25 right now), and the tool gets more popular, people will be able to share some nice profiles :)
