### ISSUE TITLE
FR: Set loop points on uploaded samples

### ISSUE THREAD

**Issue by subatomiq** [kaythomas0/noisedash#8]
Hi, this is a great tool with heaps of potential.
It would be excellent to be able to set/mark loop points on uploaded samples, 
since not every sample is pre-cut as a loop

**Comment by KevinThomas0** [comment]
Thanks, I think that's a good idea. I'll add it to the TODO. It's gonna require a moderate amount of work because that probably means implementing some sort of playback preview.

**Comment by kaythomas0** [comment]
Added in v0.2.0

**Comment by subatomiq** [comment]
that's great - thank you for adding this
