### ISSUE TITLE
Unable to Start on Raspberry Pi 4 - Ubuntu 21.10

### ISSUE THREAD

**Issue by Firestorrrm** [kaythomas0/noisedash#9]
Hello, 

I'm unable to launch the container on a Raspberry Pi running Ubuntu 21.10. 

`Linux raspberrypi 5.13.0-1009-raspi #10-Ubuntu SMP PREEMPT Mon Oct 25 13:58:43 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

Log entry for container:
`standard_init_linux.go:228: exec user process caused: exec format error`

Thanks

**Comment by KevinThomas0** [comment]
Sorry, I've only tested the docker image with the `amd64` cpu architecture, I think I would need to make a separate image for Raspberry Pi. Maybe I can consider trying that in the future.

In the mean time though, it might work on Raspberry Pi if you build it from source, which I have instructions for in the README.

**Comment by kaythomas0** [comment]
@Firestorrrm I pushed an armv7 image to docker hub. I tested it on my Raspberry Pi 4 and everything seemed to be working well!

Here's the image: `noisedash/noisedash:latest-armv7`

Feel free to let me know if you run into issues with it.
